Task from eugene1
kpeatiBwik/java_ort_vitaha pull request #19
Opened 2016-11-14 09:38 UTC by kpeatiBwik

Added Task from eugene1

2016-11-17 18:13 UTC, strazhkoe requested changes

2016-11-17 18:13 UTC, strazhkoe commented on src/taskFromEugene1/UseDots.java
> +	private static void printEmployees(Dots[] dots) {
print employees?

2016-11-17 19:19 UTC, kpeatiBwik commented
fix

2016-11-20 11:30 UTC, strazhkoe approved these changes

2016-11-20 11:30 UTC, merged