Task from eugene2
kpeatiBwik/java_ort_vitaha pull request #20
Opened 2016-11-15 10:55 UTC by kpeatiBwik

added Task from eugene2

2016-11-17 18:31 UTC, strazhkoe requested changes

2016-11-17 18:31 UTC, strazhkoe commented on src/taskFromEugene2/Student.java
> +	public String result(int[] result) {
Вынеси этот метод из этого класса. Студент не должен содержать логику начисления стипендии. Студент должен только хранить инфу о себе.

2016-11-17 19:20 UTC, kpeatiBwik commented
fix

2016-11-20 11:32 UTC, strazhkoe requested changes

2016-11-20 11:32 UTC, strazhkoe commented on src/taskFromEugene2/GrantsForStudent.java
> +	private static String result(int[] result) {
Придумай более информативное имя метода. Если программа будет расширяться, то это название перемешается с другими и станет совсем неинформативным

2016-11-22 08:24 UTC, kpeatiBwik commented
fix

2016-11-25 15:13 UTC, strazhkoe approved these changes

2016-11-25 15:13 UTC, merged