Task from Eugene5
kpeatiBwik/java_ort_vitaha pull request #22
Opened 2016-11-17 15:23 UTC by kpeatiBwik

Added Task from Eugene5

2016-11-20 11:07 UTC, strazhkoe requested changes

2016-11-20 11:07 UTC, strazhkoe commented on src/taskFromEugene5/MagicArray.java
> +	private int Array[] = new int[0];
Поля нужно называть с маленькой буквы

2016-11-20 11:07 UTC, strazhkoe commented on src/taskFromEugene5/MagicArray.java
> +		Array = array;
Тут нужно копировать переданный массив

2016-11-20 11:07 UTC, strazhkoe commented on src/taskFromEugene5/MagicArray.java
> +		return Array;
возвращать надо копию массива

2016-11-22 08:30 UTC, kpeatiBwik commented on src/taskFromEugene5/MagicArray.java
> +		Array = array;
fix

2016-11-22 08:30 UTC, kpeatiBwik commented on src/taskFromEugene5/MagicArray.java
> +	private int Array[] = new int[0];
fix

2016-11-22 08:38 UTC, kpeatiBwik commented on src/taskFromEugene5/MagicArray.java
> +		return Array;
fixed

2016-11-26 21:24 UTC, strazhkoe commented on src/taskFromEugene5/MagicArray.java
> +		System.arraycopy(array, 0, this.array, 0, array.length);
Тут не будет выхода за границу массива, если this.array.length < array.length?

2016-12-01 11:59 UTC, strazhkoe approved these changes

2016-12-01 11:59 UTC, merged