Task from eugene6
kpeatiBwik/java_ort_vitaha pull request #23
Opened 2016-11-27 15:04 UTC by kpeatiBwik

Task from eugene6
не добавил ещё проверку на пустую базу

2016-11-30 07:01 UTC, strazhkoe requested changes

2016-11-30 07:01 UTC, strazhkoe commented on src/taskFromEugene6/UseUserLibrary.java
> +				menu();
Рекурсия. Тут ей не место

2016-11-30 07:01 UTC, strazhkoe commented on src/taskFromEugene6/UseUserLibrary.java
> +			System.exit(0);
Вынеси логику выхода из программы в метод. Попрощайся с пользователем. Если хочешь выйти из программы - везде вызывай этот метод

2016-11-30 07:01 UTC, strazhkoe commented on src/taskFromEugene6/UseUserLibrary.java
> +			case 1:
Magic number

2016-11-30 07:01 UTC, strazhkoe commented on src/taskFromEugene6/UserLibrary.java
> +	public String get_name() {
нижние подчеркивания в названиях get и set методов надо убрать

2016-11-30 07:01 UTC, strazhkoe commented on src/taskFromEugene6/Faculty.java
> +public enum Faculty {
Нужно переделать немного архитектуру так, чтобы добавление нового факультета было максимально простым. Сейчас изменения нужно вносить в несколько мест кода программы

2016-11-30 08:36 UTC, kpeatiBwik commented on src/taskFromEugene6/UserLibrary.java
> +	public String get_name() {
хорошо, уберу, только смысл тогда делать поля с нижним подчеркиванием. потом по ним криво генерятся геттеры и сеттеры

2016-11-30 08:36 UTC, kpeatiBwik commented on src/taskFromEugene6/UseUserLibrary.java
> +			case 1:
тут именно название переменной тебе не понравилось?

2016-11-30 08:37 UTC, kpeatiBwik commented on src/taskFromEugene6/UseUserLibrary.java
> +				menu();
не знаю другого способа вернуться обратно в предыдущее меню

2016-11-30 08:43 UTC, kpeatiBwik commented on src/taskFromEugene6/Faculty.java
> +public enum Faculty {
в любом случае пункт в меню придется добавлять, без разницы в Enumе будет добавляться факультет или в какой нибудь константе

2016-11-30 08:45 UTC, kpeatiBwik commented on src/taskFromEugene6/UseUserLibrary.java
> +			System.exit(0);
fixed

2016-11-30 08:49 UTC, kpeatiBwik commented on src/taskFromEugene6/UseUserLibrary.java
> +			case 1:
fixed

2016-11-30 08:55 UTC, kpeatiBwik commented on src/taskFromEugene6/UserLibrary.java
> +	public String get_name() {
fixed

2016-11-30 09:14 UTC, strazhkoe commented on src/taskFromEugene6/UseUserLibrary.java
> +				menu();
return;

2016-11-30 10:03 UTC, kpeatiBwik commented on src/taskFromEugene6/UseUserLibrary.java
> +				menu();
fixed

2016-11-30 13:36 UTC, kpeatiBwik commented on src/taskFromEugene6/Faculty.java
> +public enum Faculty {
переделал архитектуру. fixed

2016-12-01 12:01 UTC, strazhkoe commented on src/taskFromEugene6/UserLibrary.java
> +	public String get_name() {
Чтоб генерились не криво, надо настроить Code Style в эклипсе

2016-12-01 12:04 UTC, strazhkoe approved these changes

2016-12-01 12:04 UTC, merged