Task from eugene11
kpeatiBwik/java_ort_vitaha pull request #25
Opened 2016-12-16 00:16 UTC by kpeatiBwik

Task from eugene11
done

2016-12-16 00:17 UTC, kpeatiBwik commented
можно смотреть)

2016-12-17 11:28 UTC, strazhkoe requested changes
Добавь javadoc к пабликам

2016-12-17 11:28 UTC, strazhkoe commented on src/taskFromEugene11/Employee.java
> +	public abstract void salary(double x);
что должен делать этот метод и что такое x?

2016-12-25 21:14 UTC, strazhkoe requested changes

2016-12-25 21:14 UTC, strazhkoe commented on src/taskFromEugene11/Employee.java
> +	protected double _salary;
Поле не должно быть protected. Должно быть private

2016-12-26 08:25 UTC, kpeatiBwik commented on src/taskFromEugene11/Employee.java
> +	protected double _salary;
если сделать приват, поле не будет видно в наследниках

2017-01-08 10:20 UTC, strazhkoe approved these changes

2017-01-08 10:20 UTC, merged