Added Task_11_143
kpeatiBwik/java_ort_vitaha pull request #9
Opened 2016-11-03 19:23 UTC by kpeatiBwik

Added Task_11_143

ps. я мог бы конечно перебирать массив руками и искать максимальный, но зачем, если можно сделать проще ;)

2016-11-05 13:26 UTC, strazhkoe requested changes

2016-11-05 13:26 UTC, strazhkoe commented on src/java_ort_vitaha/Task_11_143.java
> +        Arrays.sort(mass);
Попробуй без сортировки. Это изменяет исходный массив. Копировать его тоже нельзя - это будет бить по производительности. Плюс ты не поменял знак максимального элемента

2016-11-05 19:53 UTC, kpeatiBwik commented on src/java_ort_vitaha/Task_11_143.java
> +        Arrays.sort(mass);
как не поменял? я же при заполнении массива, каждый элемент по модулю беру. зы. пробовал без модуля, там минус существует )

2016-11-05 20:55 UTC, strazhkoe commented on src/java_ort_vitaha/Task_11_143.java
> +        Arrays.sort(mass);
Да, теперь вижу. Надо было исходный массив вывести на экран, чтоб было видно, что было и что стало. Ну на на счет без Arrays.sort и копирования - подумай над этим

2016-11-08 20:16 UTC, strazhkoe requested changes

2016-11-08 20:16 UTC, strazhkoe commented on src/java_ort_vitaha/Task_11_143.java
> +				mass[i] = Math.abs(mass[i]);
Тут непонятно, зачем генерировать отрицательные числа, а потом брать их по модулю. В условии задачи написано: найти максимальное по модулю число и изменить его знак. Например: если есть массив {5, 4, 1, -7, -3} - то максимальное по модулю число - (-7). У него нужно поменять знак. Получаем {5, 4, 1, 7, -3}. Если исходный массив {15, 23, 11, -4, -2} - то получится {15, -23, 11, -4, -2}.

2016-12-05 09:30 UTC, kpeatiBwik commented
тут все пофикшено)

2016-12-11 11:18 UTC, merged